// These are renderer messages, not replacement implementations of Lua APIs.
export const message = (action, data = {}, after = 0) => ({ action, data, ...(after ? { after } : {}) });
const m = message;
const scenarios = [];
const add = (id, group, title, description, messages, extra = {}) => scenarios.push({ id, group, title, description, messages, ...extra });
export const positions = ['top-right', 'top-left', 'top', 'bottom-right', 'bottom-left', 'bottom'];
const notice = (type = 'info', more = {}) => ({ id: 'sample', title: 'Equipment updated', description: 'Your patrol loadout is ready to collect.', type, duration: 8000, showDuration: true, ...more });
const prompt = (id = 'sample', more = {}) => ({ id, owner: 'browser-lab', key: 'E', label: 'Inspect equipment', ...more });
const world = (more = {}) => prompt('world', { x: .5, y: .5, distance: 1.4, ...more });
const menuOptions = [
    { label: 'Collect equipment', description: 'Select to record a mock callback.' },
    { label: 'Patrol mode', values: ['Standard', 'Night patrol', 'Emergency'], defaultIndex: 1 },
    { label: 'Audio feedback', checked: true, description: 'Toggle with Space.' },
    { label: 'Installation', progress: 65, description: 'Embedded progress: 65%.' },
    { label: 'Empty progress', progress: 0 },
    { label: 'Completed installation', progress: 100 },
    { label: 'A longer equipment name that tests truncation at smaller resolutions', description: 'A deliberately long description to inspect wrapping, scrolling, alignment, and the final action.' }
];
const menu = (more = {}) => ({ id: 'lab-menu', session: 1, revision: 1, title: 'Field equipment', subtitle: 'Browser specimen', position: 'top-right', options: menuOptions, ...more });
const choices = [{ value: 'standard', label: 'Standard' }, { value: 'extended', label: 'Extended configuration for night patrol' }];
const values = { enabled: true, mode: 'standard', accent: 'mint', volume: 65, name: 'Patrol', callsign: 'ALPHA 01', sound: 'click', advanced: 25, conditional: 'Visible while enabled' };
export const settingsTabs = [
    { id: 'lab', label: 'Library fixtures', values, defaults: { ...values, volume: 50, name: 'Default' }, fields: [
        { key: 'enabled', type: 'toggle', label: 'Enable feedback', section: 'General' },
        { key: 'mode', type: 'select', label: 'Operation', options: choices, section: 'General' },
        { key: 'accent', type: 'color', label: 'Accent', options: [{ value: 'mint', label: 'Mint' }, { value: 'paper', label: 'Paper' }], section: 'General' },
        { key: 'volume', type: 'slider', label: 'Volume', min: 0, max: 100, step: 5, suffix: '%', section: 'General' },
        { key: 'name', type: 'text', label: 'Profile name', maxLength: 40, section: 'Profile' },
        { key: 'callsign', type: 'input', label: 'Callsign', placeholder: 'Enter callsign', section: 'Profile' },
        { key: 'actions', type: 'buttons', label: 'Actions', buttons: [{ value: 'ping', label: 'Test callback' }], section: 'Profile' },
        { key: 'sound', type: 'soundList', label: 'Sound preset', options: [{ value: 'click', label: 'Click', name: 'SELECT', set: 'HUD_FRONTEND_DEFAULT_SOUNDSET' }, { value: 'back', label: 'Back', name: 'BACK', set: 'HUD_FRONTEND_DEFAULT_SOUNDSET' }], section: 'Audio' },
        { key: 'advanced', type: 'slider', label: 'Advanced intensity', min: 0, max: 100, advanced: true, section: 'Advanced' },
        { key: 'conditional', type: 'text', label: 'Conditional field', showWhen: { enabled: true }, section: 'General' }
    ] },
    { id: 'empty', label: 'Empty tab', values: {}, defaults: {}, fields: [] }
];
const pause = { quickMenu: true, title: 'CORTEX', player: 'Browser player', zone: 'Mission Row', serverId: 42, safezone: 1,
    notice: 'Native actions need FiveM.', locations: [{ id: 'depot', label: 'Equipment depot', category: 'Services' }],
    pages: [{ id: 'guide', label: 'Server guide', sections: [{ title: 'Welcome', body: 'A registered consumer page with text and actions.', actions: [{ id: 'rules', label: 'Read rules' }] }] }] };
// Mirrors the built-in Cortex tab in imports/settings/client.lua (keys, sections,
// options, defaults). The bridge turns its preview values into cortex:prefs.
const cortexDefaults = { uiScale: 100, textSize: 'standard', dynamic_accent: '#8fcbbf', dynamic_opacity: 92, dynamic_motion: 'system',
    dynamic_layout: true, controlHints: true, notifyPosition: 'top-right', notifyDuration: 'standard', notifyLimit: 5, notifySound: true,
    notifySoundPreset: 'mp_idle_kick', promptMarkers: true, promptScale: 'standard', invertScroll: false, showPercent: true };
const labSounds = [['mp_idle_kick', 'MP Idle Kick', 'MP_IDLE_KICK'], ['mp_award', 'MP Award', 'MP_AWARD'], ['highlight_nav', 'Highlight Nav', 'HIGHLIGHT_NAV_UP_DOWN'],
    ['timer', 'Timer', 'TIMER'], ['atm_window', 'ATM Window', 'ATM_WINDOW']].map(([value, label, name]) => ({ value, label, name, set: 'HUD_FRONTEND_DEFAULT_SOUNDSET' }));
const positionLabels = { 'top-right': 'Top right', 'top-left': 'Top left', top: 'Top centre', 'bottom-right': 'Bottom right', 'bottom-left': 'Bottom left', bottom: 'Bottom centre' };
export const cortexSettingsTab = { id: 'cortex', label: 'CORTEX', defaults: cortexDefaults,
    values: { ...cortexDefaults, dynamic_accent: '#9bbcd3', notifyDuration: 'long', promptMarkers: false }, fields: [
        { key: 'uiScale', section: 'Interface', type: 'slider', label: 'Interface size', min: 80, max: 130, step: 5, suffix: '%', description: 'Makes every Cortex prompt, menu and notification larger or smaller.' },
        { key: 'textSize', section: 'Interface', type: 'select', label: 'Text size', description: 'Larger body text in menus, dialogs and notifications.', options: [{ value: 'standard', label: 'Standard' }, { value: 'large', label: 'Large' }] },
        { key: 'dynamic_accent', section: 'Interface', type: 'color', label: 'Shared accent', description: 'The highlight colour for selected and active items in every Cortex interface.', options: [{ value: '#8fcbbf', label: 'Mint' }, { value: '#9bbcd3', label: 'Blue' }, { value: '#bea9de', label: 'Lavender' }, { value: '#d8ba82', label: 'Amber' }, { value: '#ebe9e6', label: 'Paper' }] },
        { key: 'dynamic_opacity', section: 'Interface', type: 'slider', label: 'Surface opacity', min: 65, max: 100, step: 1, suffix: '%', description: 'How solid menus and panels look over the game.' },
        { key: 'dynamic_motion', section: 'Interface', type: 'select', label: 'Motion', description: 'Follow your system setting, keep animation to a minimum, or always animate.', options: [{ value: 'system', label: 'System' }, { value: 'reduced', label: 'Reduced' }, { value: 'full', label: 'Full' }] },
        { key: 'dynamic_layout', section: 'Interface', type: 'toggle', label: 'Avoid overlapping overlays', description: 'Moves notifications and prompts aside so they do not cover chat, the HUD or each other.' },
        { key: 'controlHints', section: 'Interface', type: 'toggle', label: 'Control hints', description: 'Show key hints under menus and prompts. A hint that is the only instruction always stays.' },
        { key: 'notifyPosition', section: 'Notifications', type: 'select', label: 'Position', description: 'Where notifications appear on screen.', options: positions.map(value => ({ value, label: positionLabels[value] })) },
        { key: 'notifyDuration', section: 'Notifications', type: 'select', label: 'Display time', description: 'How long notifications stay on screen before they leave.', options: [{ value: 'short', label: 'Short' }, { value: 'standard', label: 'Standard' }, { value: 'long', label: 'Long' }] },
        { key: 'notifyLimit', section: 'Notifications', type: 'select', label: 'Visible at once', description: 'The most notifications shown at the same time.', options: [{ value: 3, label: '3' }, { value: 5, label: '5' }, { value: 8, label: '8' }] },
        { key: 'notifySound', section: 'Notifications', type: 'toggle', label: 'Sound', description: 'Play a sound when a notification arrives.' },
        { key: 'notifySoundPreset', section: 'Notifications', type: 'soundList', label: 'Sound preset', description: 'The sound notifications use. Choosing one plays it.', options: labSounds, showWhen: { notifySound: true } },
        { key: 'promptMarkers', section: 'Prompts', type: 'toggle', label: 'Distant interaction markers', description: 'Show a small marker where you can interact before you are close enough to use it.' },
        { key: 'promptScale', section: 'Prompts', type: 'select', label: 'Prompt size', description: 'Size of interaction prompts in the world and on screen.', options: [{ value: 'small', label: 'Small' }, { value: 'standard', label: 'Standard' }, { value: 'large', label: 'Large' }] },
        { key: 'invertScroll', section: 'Prompts', type: 'toggle', label: 'Invert list scroll', description: 'Flip the mouse wheel direction when choosing between stacked prompts.' },
        { key: 'showPercent', section: 'Progress', type: 'toggle', label: 'Show percentage', description: 'Show how far along an action is next to progress bars and circles.' }
    ] };
const settings = (more = {}) => ({ session: 1, tabs: [cortexSettingsTab, ...settingsTabs], pause, ...more });
const cortexSettings = (more = {}) => settings({ pause: { ...pause, notice: '' }, tabs: [cortexSettingsTab, { ...settingsTabs[0], label: 'Police MDT' }], ...more });
const radialNames = [['Vehicle', 'car', 'Engine, doors, windows and seats.'], ['Inventory', 'box', 'Open your pockets and bag.'], ['Phone', 'phone', 'Calls, messages and apps.'], ['Keys', 'key', 'Share or revoke vehicle keys.'],
    ['Emotes', 'user', 'Play an animation.'], ['Settings', 'sliders', 'Cortex interface and controls.'], ['Radio', 'radio', 'Tune the handheld radio.'], ['House', 'house', 'Lock, enter and manage your property.'],
    ['GPS', 'pin', 'Set a waypoint.'], ['Wallet', 'money', 'Cash, cards and ID.'], ['Repair', 'wrench', 'Use a repair kit.'], ['Medical', 'heart', 'Treat yourself or others.'],
    ['Police', 'shield', 'Call for help.'], ['Favourites', 'star', 'Pinned actions.'], ['Camera', 'camera', 'Take a photo.'], ['Alerts', 'bell', 'Recent notifications.'], ['Fuel', 'fuel', 'Refuel at a pump.'], ['Lock', 'lock', 'Lock the nearest vehicle.']];
const radialItems = (count, more = {}) => Array.from({ length: count }, (_, i) => { const [label, icon, description] = radialNames[i % radialNames.length]; return { id: `item-${i}`, label: i >= radialNames.length ? `${label} ${i + 1}` : label, icon, description, ...more }; });
const radialShow = (items, more = {}) => m('radialShow', { session: 1, menuId: 'lab-radial', items, ...more });

add('overview', 'Start here', 'Shared overlays', 'Real notification, progress, help, screen prompt, and projected world prompt components. Click the stage for keyboard input.', [
    m('notify', notice()), m('progressStart', { duration: 12000, label: 'Preparing equipment', style: 'bar', position: 'bottom' }),
    m('interaction:update', { items: [prompt()] }), m('interaction:world', { items: [world({ label: 'Projected anchor' })] }),
    m('helpShow', { items: [{ value: 'E', label: 'Interact' }, { value: 'SHIFT E', label: 'Alternate' }] })
]);
add('empty', 'Start here', 'Empty / closed', 'No surfaces mounted. Use the message editor to send any NUI message.', []);
for (const type of ['info', 'inform', 'success', 'warning', 'error']) add(`notify-${type}`, 'Notifications', type, 'Timed notification with title, body, icon, and duration.', [m('notify', notice(type))]);
add('notify-types', 'Notifications', 'All status types', 'Compare each severity in a single notification stack.', ['info', 'success', 'warning', 'error'].map(type => m('notify', notice(type, { id: type, title: type, duration: 12000 }))));
for (const position of positions) add(`notify-${position}`, 'Notifications', `Position / ${position}`, 'Notification placement, independent of the playground controls.', [m('notify', notice('info', { position }))]);
add('notify-long', 'Notifications', 'Long text & plain notice', 'Wrapping, title-free text, hidden timer, and a persistent notice.', [m('notify', notice('warning', { title: 'A long notification title for narrow screen layouts', description: 'Return to the equipment depot. '.repeat(15), duration: 0, showDuration: false })), m('notify', { id: 'plain', description: 'Started cortex-subtleadditions', plain: true, hideIcon: true, duration: 8000 })]);
add('notify-keys', 'Notifications', 'Headline, keycaps & persistent', 'A title-free headline, inline [KEY] keycaps in a body, and a persistent notice with its dismiss keycap.', [m('notify', { id: 'headline', type: 'success', description: 'Vehicle stored', duration: 12000 }), m('notify', notice('info', { id: 'keys', title: 'Trunk unlocked', description: 'Press [E] to open the trunk or [G] to lock it again.', duration: 12000 })), m('notify', notice('error', { id: 'persist', title: 'Connection lost', description: 'Reconnect from the pause menu.', duration: 0 }))]);
add('notify-stack', 'Notifications', 'Stack / capacity', 'Sixteen notices arrive together to exercise the production queue cap.', Array.from({ length: 16 }, (_, i) => m('notify', notice('info', { id: `notice-${i}`, title: `Notice ${i + 1}`, duration: 15000 }))));
add('notify-limit', 'Notifications', 'Player limit & duration prefs', 'Player prefs: limit 3, lifetime x2. Two persistent notices are held past the cap (+N held); timed ones beyond it leave.', [m('cortex:prefs', { prefs: { notifyLimit: 3, notifyDuration: 2 } }), m('notify', notice('warning', { id: 'held-1', title: 'Persistent one', duration: 0 })), m('notify', notice('warning', { id: 'held-2', title: 'Persistent two', duration: 0 })), ...Array.from({ length: 4 }, (_, i) => m('notify', notice(['info', 'success', 'info', 'success'][i], { id: `limit-${i}`, title: `Timed ${i + 1}`, duration: 6000 }), 150 * (i + 1)))]);
add('notify-update', 'Notifications', 'Update, hide & clear', 'Same-ID replacement at 1.5s, hide at 3s, and clear owner at 4.5s.', [m('notify', notice('info', { duration: 0 })), m('notify', notice('success', { title: 'Same ID, updated', duration: 0 }), 1500), m('hideNotify', { id: 'sample' }, 3000), m('notify', notice('warning'), 3500), m('clearNotifications', { owner: 'cortex-lib' }, 4500)]);
for (const style of ['bar', 'circle']) for (const position of ['top', 'middle', 'bottom']) add(`progress-${style}-${position}`, 'Progress', `${style} / ${position}`, 'Timed progress. Press Escape to simulate consumer cancellation.', [m('progressStart', { duration: 10000, label: 'Installing field equipment', style, position, canCancel: true })]);
add('progress-cancel', 'Progress', 'Cancel & restart', 'Cancel after 2 seconds (sand outcome) and restart with a new label.', [m('progressStart', { duration: 12000, label: 'Cancelable work', canCancel: true }), m('progressEnd', { completed: false }, 2000), m('progressStart', { duration: 3000, label: 'Restarted work', style: 'circle' }, 3000)]);
add('progress-locked', 'Progress', 'Non-cancelable', 'Runs to completion; Backspace and Escape do not cancel this specimen. Clear stage still resets it.', [m('progressStart', { duration: 6000, label: 'Finalizing installation', canCancel: false })]);
for (const style of ['bar', 'circle']) {
    add(`progress-${style}-complete`, 'Progress', `${style} / complete`, 'Short timed action that completes: the fill pulses to paper, then leaves.', [m('progressStart', { duration: 1200, label: 'Lockpicking', style, position: 'bottom' }), m('progressEnd', { completed: true }, 1200)]);
    add(`progress-${style}-cancelled`, 'Progress', `${style} / cancelled`, 'Cancelled at about 45%: sand fill and a CANCELLED readout, then it leaves.', [m('progressStart', { duration: 4000, label: 'Repairing engine', style, position: 'bottom', canCancel: true }), m('progressEnd', { completed: false }, 1800)]);
}
add('progress-controlled', 'Progress', 'Controlled value / long label', 'A controlled value at 62% with a long label, as the debug workbench drives it.', [m('debug:walkthrough', { revision: 1, run: { index: 5, completed: 5, total: 8, id: 'sample', title: 'Notifications, progress and the controls legend' } })]);
add('progress-no-percent', 'Progress', 'Percent hidden (player pref)', 'showPercent = false: the bar and ring carry no numeric readout.', [m('cortex:prefs', { prefs: { showPercent: false } }), m('progressStart', { duration: 10000, label: 'Searching the glovebox', style: 'bar', position: 'bottom', canCancel: true })]);
add('progress-no-percent-circle', 'Progress', 'Percent hidden / circle', 'showPercent = false on the ring.', [m('cortex:prefs', { prefs: { showPercent: false } }), m('progressStart', { duration: 10000, label: 'Searching the glovebox', style: 'circle', position: 'bottom' })]);
for (const position of ['top-left', 'top-center', 'top-right', 'bottom-left', 'bottom-center', 'bottom-right']) add(`text-${position}`, 'Text & help', `Text / ${position}`, 'Text UI with its supported position, hand icon, and backdrop.', [m('textUIShow', { text: '[E] Inspect field equipment', position, icon: 'hand', backdrop: true })]);
add('text-action', 'Text & help', 'Text / action keycap', 'The common case: one [KEY] token and a short action, frameless.', [m('textUIShow', { text: '[E] Open trunk', position: 'bottom-center' })]);
add('text-multikey', 'Text & help', 'Text / multiple keys', 'Two actions and a compound key: [E] Open  [SHIFT+G] Lock.', [m('textUIShow', { text: '[E] Open trunk  [SHIFT+G] Lock', position: 'bottom-center' })]);
add('text-sentence', 'Text & help', 'Text / sentence with keycaps', 'A longer instruction in Arial with inline keycaps and the hand icon.', [m('textUIShow', { text: 'Hold [E] to pick the lock. Release early or press [BACKSPACE] to stop and keep your pick.', position: 'bottom-center', icon: 'hand' })]);
add('text-long', 'Text & help', 'Long text / no backdrop', 'Text UI wrapping and bare presentation.', [m('textUIShow', { text: 'Return to the depot for replacement equipment. '.repeat(6), position: 'bottom-center', backdrop: false })]);
add('text-hide', 'Text & help', 'Text / hide', 'Shown, then hidden at 1.5s (short exit).', [m('textUIShow', { text: '[E] Talk to the clerk', position: 'bottom-center' }), m('textUIHide', {}, 1500)]);
add('help-legend', 'Text & help', 'Legend / GRAB & BACK', 'The GTA-style controls legend: label first, keycaps after, bottom-right.', [m('helpShow', { items: [{ label: 'Grab', value: 'E' }, { label: 'Back', value: 'BACKSPACE' }] })]);
add('help-single', 'Text & help', 'Legend / one item', 'A single control.', [m('helpShow', { items: [{ label: 'Exit camera', value: 'ESC' }] })]);
for (const compact of [false, true]) add(`help-${compact ? 'compact' : 'full'}`, 'Text & help', `Help / ${compact ? 'compact' : 'full'}`, 'Single, compound, and long key labels.', [m('helpShow', { compact, items: [{ value: 'E', label: 'Inspect' }, { value: 'SHIFT E', label: 'Alternate action' }, { value: 'BACKSPACE', label: 'Cancel' }, { value: 'MOUSE1', label: 'Select' }] })]);
add('help-freecam', 'Text & help', 'Legend / eight items (freecam)', 'A real consumer strip: key groups, separators, prose values and a LEFT ALT modifier.', [m('helpShow', { items: [{ label: 'Move', value: 'W S A D' }, { label: 'Up / Down', value: 'Space Q' }, { label: 'Look', value: 'Mouse' }, { label: 'Faster', value: 'Shift' }, { label: 'Hold cursor', value: 'LEFT ALT' }, { label: 'Rotate', value: 'ARROWS' }, { label: 'Exit', value: 'Esc · Backspace' }, { label: 'Off', value: 'Recording tab' }] })]);
add('help-freecam-compact', 'Text & help', 'Legend / eight items compact', 'The same strip with compact keycaps.', [m('helpShow', { compact: true, items: [{ label: 'Move', value: 'W S A D' }, { label: 'Up / Down', value: 'Space Q' }, { label: 'Look', value: 'Mouse' }, { label: 'Faster', value: 'Shift' }, { label: 'Hold cursor', value: 'LEFT ALT' }, { label: 'Rotate', value: 'ARROWS' }, { label: 'Exit', value: 'Esc · Backspace' }, { label: 'Off', value: 'Recording tab' }] })]);
add('help-with-text', 'Text & help', 'Legend + text UI + progress', 'Everything at once: a text instruction, a running bar and the legend.', [m('textUIShow', { text: '[E] Collect evidence', position: 'bottom-center' }), m('progressStart', { duration: 12000, label: 'Bagging evidence', canCancel: true }), m('helpShow', { items: [{ label: 'Collect', value: 'E' }, { label: 'Rotate', value: 'Q E' }, { label: 'Back', value: 'BACKSPACE' }] })]);
add('debug-panel', 'Text & help', 'Telemetry panel', 'Sample data, structured values, long lines, and live update.', [m('debugPanelShow', { title: 'Cortex diagnostics', subtitle: 'Browser sample data', lines: [{ label: 'Player', value: '42' }, { label: 'Entity', value: 'Mock only' }, { label: 'State', value: { visible: true, active: true } }, 'Long diagnostic line '.repeat(8)] }), m('debugPanelUpdate', { lines: [{ label: 'Status', value: 'Updated at 2 seconds' }] }, 2000)]);
add('debug-panel-rich', 'Text & help', 'Telemetry panel / rich', 'Many rows, coloured values, an accent override and a JSON block.', [m('debugPanelShow', { title: 'Vehicle telemetry', subtitle: 'cortex-hud · sample', accentColor: 'var(--warning)', position: 'top-left', lines: [{ label: 'Model', value: 'SULTAN RS' }, { label: 'Speed', value: '82.4 km/h' }, { label: 'RPM', value: '0.742' }, { label: 'Gear', value: '3' }, { label: 'Fuel', value: '14%', color: 'var(--warning)' }, { label: 'Engine', value: '312.0', color: 'var(--error)' }, { label: 'Coords', value: '-1034.22, -2731.87, 20.17' }, { label: 'Net ID', value: '1846' }], data: { plate: 'CRTX 42', owner: 'char:381', mods: { engine: 3, brakes: 2, turbo: true } } })]);
for (const position of ['top-left', 'top-right', 'bottom-left', 'bottom-right']) add(`menu-${position}`, 'Menus', `List / ${position}`, 'Selection, values, checkbox, tooltip, and empty / partial / full inline progress. Keyboard arrows / Enter / Space / Escape.', [m('menuOpen', menu({ position }))]);
add('menu-long', 'Menus', 'Long list', 'Forty rows exercise scrolling and selection near the end.', [m('menuOpen', menu({ options: [...menuOptions, ...Array.from({ length: 33 }, (_, i) => ({ label: `Option ${i + 8}`, description: 'Scrolling specimen' }))] }))]);
add('menu-empty', 'Menus', 'Empty list', 'No options; Escape still closes the menu.', [m('menuOpen', menu({ options: [] }))]);
add('menu-update', 'Menus', 'Live row updates', 'Replaces options at 2s, then updates one row at 4s with increasing revisions.', [m('menuOpen', menu()), m('menuSetOptions', { id: 'lab-menu', session: 1, revision: 2, options: [{ label: 'Updated first row' }, { label: 'Second row' }] }, 2000), m('menuSetOption', { id: 'lab-menu', session: 1, revision: 3, index: 2, option: { label: 'Updated second row', checked: true } }, 4000)]);
const iconOptions = [
    { label: 'Vehicle keys', icon: 'key', description: 'Named icons resolve to one stroked Cortex glyph family.' },
    { label: 'Repair kit', icon: 'fa-solid fa-screwdriver-wrench', description: 'Font Awesome class strings map to the same family.' },
    { label: 'Dispatch', icon: 'shield', iconColor: 'var(--info)', values: ['Available', 'Busy', 'Off duty'] },
    { label: 'Medical', icon: 'heart', iconColor: '#df918d', checked: false },
    { label: 'Emoji fallback', icon: '🚗', description: 'Emoji render as a single-colour silhouette, never in colour.' },
    { label: 'Letter fallback', icon: 'unknown-icon', description: 'Unknown names fall back to a display-caps monogram.' },
    { label: 'No icon keeps the column' }
];
const disabledOptions = [
    { label: 'Open garage', icon: 'car' },
    { label: 'Impound (locked)', icon: 'lock', disabled: true, description: 'Disabled rows are skipped by arrows and the wheel and ignore clicks.' },
    { label: 'Share keys', icon: 'key', values: ['Nobody', 'Passengers', 'Crew'], disabled: true },
    { label: 'Auto-lock', icon: 'lock', checked: true, disabled: true },
    { label: 'Fuel level', icon: 'fuel', progress: 40, disabled: true },
    { label: 'Leave', icon: 'arrow-left' }
];
const denseOptions = Array.from({ length: 40 }, (_, i) => [
    { label: `Outfit ${i + 1}`, description: 'Plain row.' },
    { label: `Variation ${i + 1}`, values: ['Default', 'Alternate', 'Worn', 'Custom palette with a long name'], defaultIndex: 2 },
    { label: `Accessory ${i + 1}`, checked: i % 2 === 0 },
    { label: `Wear ${i + 1}`, progress: (i * 7) % 101 }
][i % 4]);
add('menu-icons', 'Menus', 'Icons & colour', 'Fixed icon column: named glyphs, Font Awesome class strings, iconColor, emoji silhouette and monogram fallback.', [m('menuOpen', menu({ position: 'top-left', title: 'Vehicle', subtitle: 'Owner actions', options: iconOptions }))]);
add('menu-disabled', 'Menus', 'Disabled rows', 'Disabled plain, value, check and progress rows. Arrow past them; clicks and Enter are ignored.', [m('menuOpen', menu({ position: 'top-left', title: 'Garage', subtitle: 'Pillbox Hill', options: disabledOptions }))]);
add('menu-value-selected', 'Menus', 'Value row selected', 'Starts on a value row: chevrons, Change hint, and the value description. Left/right or click a chevron.', [m('menuOpen', menu({ position: 'top-left', startIndex: 2, options: [menuOptions[0], { label: 'Patrol mode', values: [{ label: 'Standard', description: 'Normal patrol response.' }, { label: 'Night patrol', description: 'Reduced lights and sirens after dark.' }, { label: 'Emergency', description: 'Code 3 response.' }], defaultIndex: 2 }, ...menuOptions.slice(2)] }))]);
add('menu-check-selected', 'Menus', 'Check row selected', 'Starts on a check row: the paper-face check mark and the Space Toggle hint.', [m('menuOpen', menu({ position: 'top-left', startIndex: 3 }))]);
add('menu-long-description', 'Menus', 'Long label & description', 'Starts on the long row: the label ellipsizes in the list and repeats in full above a clamped description.', [m('menuOpen', menu({ position: 'top-left', startIndex: 7, options: [...menuOptions.slice(0, 6), { ...menuOptions[6], description: 'A deliberately long description to inspect wrapping, scrolling, alignment, and the final action. '.repeat(4) }] }))]);
add('menu-game-controls', 'Menus', 'Game controls mode', 'gameControls = true: WHEEL / LMB / RMB legend. Lua forwards input as menuNav; this scene sends a down, a right and a select.', [m('menuOpen', menu({ position: 'top-left', gameControls: true })), m('menuNav', { session: 1, input: 'down' }, 1200), m('menuNav', { session: 1, input: 'right' }, 2000), m('menuNav', { session: 1, input: 'down' }, 2800)]);
add('menu-locked', 'Menus', 'Not closable', 'canClose = false: no Back / Close hints, Escape and Backspace are ignored.', [m('menuOpen', menu({ position: 'top-left', canClose: false, title: 'Choose a spawn', subtitle: 'Required' }))]);
add('menu-dense', 'Menus', 'Dense list / 720p', 'Forty mixed rows starting mid-list. Review at 1280x720: the window shrinks to the rows that fit, edges fade and the rail tracks. Home/End/PgUp/PgDn and the wheel move.', [m('menuOpen', menu({ position: 'top-left', title: 'Wardrobe', subtitle: 'Saved outfits', startIndex: 18, options: denseOptions }))]);
for (const [id, count, title, description] of [['basic', 6, 'Six actions', 'Named icons and descriptions. Move the mouse anywhere past the dead zone to aim; the hub names the choice.'], ['two', 2, 'Two actions', 'Two halves, top and bottom.'], ['eight', 8, 'Eight actions', 'A full page; 1-8 pick directly.'], ['pages', 18, 'Paged 18', 'Three pages of eight slots: dots and Q / E under the wheel, wheel or Q / E to page. The last page keeps ghost slots so directions do not move.'], ['empty', 0, 'Empty', 'No actions: a ghost ring and the close hint.'], ['single', 1, 'Single action', 'One action fills the ring; any direction selects it.']]) add(`radial-${id}`, 'Radial', `Wheel / ${title}`, description, [radialShow(radialItems(count))]);
add('radial-compact', 'Radial', 'Wheel / compact-control', 'The smaller hardware-control wheel: icons only, the hub carries the label, no legend.', [radialShow(radialItems(6), { appearance: 'compact-control' })]);
add('radial-submenu', 'Radial', 'Submenu / back', 'Vehicle and Keys open mock submenus (chevrons). The breadcrumb names the path; RMB, Backspace or the centre returns and re-selects the parent item.', [radialShow(radialItems(6).map((item, i) => i === 0 || i === 3 ? { ...item, menu: `lab-child-${i}` } : item))], { behavior: 'radial-submenu' });
add('radial-disabled', 'Radial', 'Disabled items', 'Two disabled actions: dim, no flip or mint arc when aimed at, clicks and number keys ignored.', [radialShow(radialItems(6).map((item, i) => i === 1 || i === 4 ? { ...item, disabled: true, description: i === 1 ? 'Your hands are full.' : undefined } : item))]);
add('radial-long', 'Radial', 'Long labels', 'Long labels clamp to two lines in the slip and appear in full in the hub. Review at 1280x720 too.', [radialShow(['Open the complete vehicle equipment configuration', 'Inventory', 'Request emergency medical services', 'Keys', 'Supercalifragilisticexpialidocious', 'Settings and preferences for the Cortex interface'].map((label, i) => ({ id: `long-${i}`, label, icon: radialNames[i][1], description: 'A deliberately long description that must wrap inside the hub without covering the slips or running past three lines of copy.' })))]);
add('radial-glyphs', 'Radial', 'Glyph icons', 'Single-character icons render in display type; emoji become a silhouette; unknown names fall back to a monogram; no icon gives the label the room.', [radialShow([{ id: 'g1', label: 'Seat one', icon: '1' }, { id: 'g2', label: 'Seat two', icon: '2' }, { id: 'g3', label: 'Help', icon: '?' }, { id: 'g4', label: 'Taxi', icon: '🚕' }, { id: 'g5', label: 'Engine', icon: 'engine' }, { id: 'g6', label: 'No icon' }])]);
const alertBase = { session: 1, header: 'Replace equipment?', content: 'Your current equipment will be returned to the depot.', labels: { confirm: 'Replace', cancel: 'Keep current' } };
for (const [id, title, data] of [
    ['confirm', 'Confirm / cancel', {}],
    ['confirm-only', 'Confirm only', { cancel: false, header: 'Shift ended', content: 'Your equipment was returned to the depot.\nCollect it again at the start of your next shift.', labels: { confirm: 'Understood' } }],
    ['long', 'Long copy / scroll', { content: 'Your current profile will be replaced with the depot standard.\n\n' + 'Attachments, ammunition and radio presets saved on this profile are removed. '.repeat(14) + '\n\nThis cannot be undone.' }],
    ['centered', 'Centered', { centered: true, header: 'Clock in?', content: 'You are about to start a patrol shift.' }],
    ['plain', 'No header', { header: '' }]
]) add(`alert-${id}`, 'Dialogs', `Alert / ${title}`, 'Enter confirms, Escape cancels, Tab moves the paper face; arrows/Page keys scroll long copy. Toggle callback failure to see the inline error.', [m('alertDialog', { ...alertBase, ...data })]);
const formFields = [
    { name: 'name', type: 'input', label: 'Profile name', required: true, placeholder: 'Name this loadout' },
    { name: 'note', type: 'text', label: 'Notes', description: 'Shown to other officers when they inspect the locker.' },
    { name: 'count', type: 'input', inputType: 'number', label: 'Quantity', min: 1, max: 10, step: 1 },
    { name: 'email', type: 'input', inputType: 'email', label: 'Email', placeholder: 'name@example.com' },
    { name: 'password', type: 'input', inputType: 'password', label: 'Locker code', description: 'Use Show to check what you typed.' },
    { name: 'enabled', type: 'checkbox', label: 'Audio feedback', description: 'Play a click when the locker opens.' },
    { name: 'mode', type: 'select', label: 'Operation', options: choices, required: true }
];
add('context-form', 'Dialogs', 'Form / all fields', 'Text, notes, bounded number stepper, email, password reveal, checkbox, dropdown, descriptions and required markers.', [m('contextMenu', { session: 1, title: 'Equipment profile', fields: formFields, values: { name: 'Patrol', count: '2', enabled: true, mode: 'standard' } })]);
add('context-required', 'Dialogs', 'Form / required empty', 'Required fields start empty. Press Enter or Confirm to see inline errors and focus move to the first invalid field.', [m('contextMenu', { session: 1, title: 'Register vehicle', fields: [
    { name: 'plate', type: 'input', label: 'Plate', required: true, placeholder: 'e.g. 46EEK572' },
    { name: 'owner', type: 'select', label: 'Owner', required: true, options: ['Personal', 'Department', 'Impound'] },
    { name: 'mileage', type: 'input', inputType: 'number', label: 'Mileage', min: 0, max: 999999 }
] })]);
add('context-number', 'Dialogs', 'Form / number stepper', 'Stepper with min 0.5, max 5, step 0.5: buttons, Arrow keys (Shift x10), clamp at bounds and out-of-range typing.', [m('contextMenu', { session: 1, title: 'Fuel order', fields: [
    { name: 'litres', type: 'input', inputType: 'number', label: 'Jerry cans', min: 0.5, max: 5, step: 0.5, required: true, description: 'Half-can steps. Arrow keys step too.' },
    { name: 'tip', type: 'input', inputType: 'number', label: 'Tip', min: 0, placeholder: '0' },
    { name: 'priority', type: 'checkbox', label: 'Priority delivery' }
], values: { litres: '1.5' } })]);
add('context-long', 'Dialogs', 'Form / long (720p scroll)', 'Fourteen fields: the body scrolls between a fixed header and actions with fading edges. Check at 720p.', [m('contextMenu', { session: 1, title: 'Incident report', labels: { confirm: 'File report', cancel: 'Discard' }, fields: Array.from({ length: 14 }, (_, i) => i % 5 === 3
    ? { name: `flag${i}`, type: 'checkbox', label: `Flag ${i + 1}: follow-up required` }
    : i % 5 === 4 ? { name: `pick${i}`, type: 'select', label: `Category ${i + 1}`, options: choices }
    : { name: `line${i}`, type: 'input', label: `Detail ${i + 1}`, required: i === 0, description: i === 1 ? 'A description under the label, before the well.' : '' }) })]);
add('context-empty', 'Dialogs', 'Empty form', 'No fields, with working confirm and cancel controls.', [m('contextMenu', { session: 1, title: 'Empty form', fields: [] })]);
add('interactions-screen', 'Interactions', 'Screen / key labels', 'All eight screen slots with common keycap widths.', [m('interaction:update', { items: ['E', 'SHIFT E', 'BACKSPACE', 'MOUSE1', 'F7', 'SPACE', 'CTRL', '?'].map((key, i) => prompt(`key-${i}`, { key, label: `Action ${i + 1}` })) })]);
add('interactions-target', 'Interactions', 'Target panel', 'Shared target-panel presentation with multiple actions.', [m('interaction:update', { items: [prompt('talk', { label: 'Talk', panel: { id: 'person', label: 'STRANGER', variant: 'target' } }), prompt('inspect', { key: 'G', label: 'Inspect', panel: { id: 'person', label: 'STRANGER', variant: 'target' } })] })]);
for (const type of ['world', 'entity', 'entity-bone']) add(`anchor-${type}`, 'Interactions', `Anchor / ${type}`, `Projected ${type} fixture. The browser receives screen coordinates; real entity resolution and projection require FiveM.`, [m('interaction:world', { items: [world({ label: `${type} anchor` })] })]);
add('anchor-stack', 'Interactions', 'World / shared anchor stack', 'Four actions at exactly the same projected anchor with no group field (older renderer output) still stack as one list.', [m('interaction:world', { items: Array.from({ length: 4 }, (_, i) => world({ id: `world-${i}`, label: `Nearby action ${i + 1}`, key: ['E', 'G', 'H', 'F'][i] })) })]);
add('anchor-vehicle', 'Interactions', 'Vehicle access list', 'cortex-hud clone-key and smash-window rows keep their icons inside the shared list anatomy. Unique keys: no wheel.', [m('interaction:world', { items: [world({ id: 'vehicle-clone-key', owner: 'cortex-hud', label: 'Clone key', key: 'E', group: 'cortex-hud:vehicle-clone-key', selected: true, x: .56, y: .46 }), world({ id: 'vehicle-smash-window', owner: 'cortex-hud', label: 'Smash window', key: 'G', holdDuration: 1500, group: 'cortex-hud:vehicle-clone-key', x: .56, y: .46 })] })]);
add('anchor-visibility', 'Interactions', 'Range, off-screen & deletion', 'Simulated renderer output: visible, absent at 2s, visible at the edge at 3s, absent at 5s. Does not run Lua range checks.', [m('interaction:world', { items: [world()] }), m('interaction:world', { items: [] }, 2000), m('interaction:world', { items: [world({ x: .95, distance: 4.8 })] }, 3000), m('interaction:world', { items: [] }, 5000)]);
add('anchor-hold', 'Interactions', 'Hold, cancel & complete', 'Hold E in the stage. Release early to cancel. Completion is a simulated consumer timer, not authorization.', [m('interaction:world', { items: [world({ holdDuration: 2000 })] })], { behavior: 'hold' });
add('interaction-collision', 'Interactions', 'Arbitration output', 'Displays one winner, then a replacement winner. Actual priority and ownership arbitration runs in Lua.', [m('interaction:update', { items: [prompt('winner', { label: 'Higher-priority winner' })] }), m('interaction:update', { items: [prompt('next', { label: 'Next eligible owner' })] }, 2500)]);
// Two-tier world prompts, as client/interaction_renderer.lua sends them: markers
// carry no label/key; list rows share `group` and the head's anchor.
const marker = (id, x, y, fade, distance = 6) => ({ id, owner: 'browser-lab', tier: 'marker', x, y, fade, distance });
const listRows = (rows, { selected = 0, x = .5, y = .45, focused = true, distance = 1.2, group = 'browser-lab:list' } = {}) => rows.map((row, i) => world({
    group, x, y, distance, focused, selected: i === selected,
    active: row.key !== rows[selected].key || i === selected, ...row
}));
const fridgeRows = [['logger', 'Logger beer'], ['lavazas', 'Lavazas beer'], ['berry', 'Blitz berry smoothie'], ['green', 'Blitz green smoothie'], ['shake', 'Brookli shake']].map(([id, label]) => ({ id, label, key: 'E' }));
const grabHelp = m('helpShow', { items: [{ value: 'E', label: 'Grab' }, { value: 'BACKSPACE', label: 'Back' }] });
add('interactions-markers', 'Interactions', 'Markers / distances', 'Distant anchors as markers at three fades (near, mid, far) beside one full prompt. Markers never carry a label.', [m('interaction:world', { items: [world({ x: .42, y: .52, label: 'Open trunk' }), marker('near', .6, .44, .9), marker('mid', .7, .5, .5, 9), marker('far', .78, .41, .1, 14)] })]);
add('interactions-grow', 'Interactions', 'Marker -> prompt growth', 'The same anchor as a marker, growing into the prompt at 1.2 s, shrinking back at 3 s, growing again at 4.5 s.', [
    m('interaction:world', { items: [marker('world', .5, .5, .8, 3.4)] }),
    m('interaction:world', { items: [world({ label: 'Open door' })] }, 1200),
    m('interaction:world', { items: [marker('world', .5, .5, .9, 3.2)] }, 3000),
    m('interaction:world', { items: [world({ label: 'Open door' })] }, 4500)
]);
add('interactions-list-2', 'Interactions', 'List / two rows', 'Two same-key actions at one spot merge; the selected row owns E, the wheel moves the selection.', [m('interaction:world', { items: listRows([{ id: 'sit', label: 'Sit down', key: 'E' }, { id: 'lean', label: 'Lean on wall', key: 'E' }]) })], { behavior: 'list' });
add('interactions-list-5', 'Interactions', 'List / five rows (fade)', 'Five rows: four visible, the fifth peeks and the rail fades out below. Scroll the wheel in the stage.', [m('interaction:world', { items: listRows(fridgeRows, { selected: 1 }) })], { behavior: 'list' });
add('interactions-list-scrolled', 'Interactions', 'List / scrolled to the end', 'Selection on the last row: the window slides, the rail fades above.', [m('interaction:world', { items: listRows(fridgeRows, { selected: 4 }) })], { behavior: 'list' });
add('interactions-list-mixed', 'Interactions', 'List / mixed keys', 'Two E rows compete; the G and H rows own their keys and keep a small disc.', [m('interaction:world', { items: listRows([{ id: 'take', label: 'Take bottle', key: 'E' }, { id: 'drink', label: 'Drink here', key: 'E' }, { id: 'inspect', label: 'Inspect label', key: 'G' }, { id: 'kick', label: 'Kick over', key: 'H', holdDuration: 1200 }]) })], { behavior: 'list' });
add('interactions-list-hold', 'Interactions', 'List / hold on the selected row', 'The hold ring runs on the selected disc (3 s). The wheel is frozen while it runs.', [m('interaction:world', { items: listRows([{ id: 'pick', label: 'Pick lock', key: 'E', holdDuration: 3000 }, { id: 'knock', label: 'Knock', key: 'E' }], { selected: 0 }).map((row, i) => i === 0 ? { ...row, holdActive: true, holdRevision: 1 } : row) })]);
add('interactions-list-edge', 'Interactions', 'List / right edge + low', 'A list anchored near the right and bottom edges flips its labels and stays inside the viewport.', [m('interaction:world', { items: listRows(fridgeRows.slice(0, 3), { x: .9, y: .93 }) })], { behavior: 'list' });
add('interactions-fridge', 'Interactions', 'Fridge (reference)', 'The GTA-style merged list over the fridge with the help legend GRAB E / BACK BACKSPACE bottom-right.', [m('interaction:world', { items: listRows(fridgeRows, { selected: 1, x: .27, y: .465 }) }), grabHelp], { behavior: 'list' });
add('interactions-screen-help', 'Interactions', 'Screen prompts + help legend', 'Screen prompts lift above the bottom-right help legend instead of overlapping it.', [m('interaction:update', { items: [prompt('trunk', { label: 'Open trunk' }), prompt('hood', { key: 'G', label: 'Open hood' })] }), grabHelp]);
add('settings-all', 'Settings', 'All field types', 'Search, tabs, sections, advanced and conditional fields, reset, preview, Apply, Save, and Discard. Persistence is browser-only.', [m('settingsOpen', settings())]);
add('settings-cortex', 'Settings', 'Cortex tab', 'The built-in player preferences: Interface, Notifications, Prompts and Progress. Interface size and text size preview live through cortex:prefs; Discard rolls them back.', [m('settingsOpen', cortexSettings())]);
add('settings-scrim', 'Settings', 'Scrim over a bright scene', 'Pick the bright or image backdrop: the 55% ink scrim must keep every row legible. The heavy game blur is native (client/pause.lua) and cannot appear in a browser.', [m('notify', notice('info', { duration: 60000 })), m('settingsOpen', cortexSettings())]);
add('settings-720p', 'Settings', 'Cortex tab / 720p', 'Review at 1280x720: header, tabs, section index, rows and the action footer fit without clipping; the list scrolls inside its slip.', [m('settingsOpen', cortexSettings())]);
add('settings-empty', 'Settings', 'No registered tabs', 'Empty settings registry.', [m('settingsOpen', settings({ tabs: [] }))]);
add('settings-many', 'Settings', 'Many tabs & long content', 'Long tab labels, scrolling fields, search, and empty results.', [m('settingsOpen', settings({ tabs: Array.from({ length: 12 }, (_, i) => ({ ...settingsTabs[0], id: `tab-${i}`, label: `Resource ${i + 1} configuration`, fields: [...settingsTabs[0].fields, ...Array.from({ length: 20 }, (_, n) => ({ key: `extra-${n}`, type: 'toggle', label: `Extended field ${n + 1} with a long readable label`, section: 'More fields' }))] })) }))]);
add('settings-failure', 'Settings', 'Failed preview / save', 'The next user callback fails once. Check rollback or error feedback, then retry. Readiness callbacks still succeed.', [m('settingsOpen', settings())], { failNext: true });
add('pause-home', 'Quick menu', 'Home & native handoffs', 'Quick menu, guide, locations, and disconnect UI. Native game actions return an explicit unavailable response.', [m('settingsOpen', settings({ page: 'home' }))]);
const skillConfig = (type, more = {}) => ({ type, label: type === 'sequence' ? 'Enter the sequence' : type === 'trace' ? 'Turn the lock' : type === 'hold' ? 'Charge the mechanism' : 'Set the tension', key: 'E', keys: ['W', 'A', 'S', 'D'], duration: 15000, speed: .5, targetStart: .55, targetSize: .2, direction: 'upper', decay: .12, interactionId: 'mash', ...more });
for (const type of ['radial', 'hold', 'sequence', 'trace', 'mash']) add(`skill-${type}`, 'Skill checks', type, type === 'trace' ? 'Sweep the mouse once: right, up and over to the left. The browser mirrors the Lua virtual knob (1 unit = 200 px); FiveM feel needs in-game checks.' : type === 'mash' ? 'Repeatedly press E. Browser-only progress drives the real interaction keycap.' : 'Play the real JavaScript skill engine. Success, missed input, timeout, and Escape appear in the callback log.', [
    ...(type === 'mash' ? [m('interaction:world', { items: [world({ id: 'mash', label: 'Build pressure' })] })] : []),
    m('skill:open', { session: 1, owner: 'browser-lab', config: skillConfig(type) })
], { behavior: `skill-${type}` });
add('skill-trace-lower', 'Skill checks', 'Trace / lower sweep', 'Lower direction: right, down and under to the left.', [m('skill:open', { session: 1, owner: 'browser-lab', config: skillConfig('trace', { direction: 'lower', label: 'Seat the bearing' }) })], { behavior: 'skill-trace' });
add('skill-trace-invalid', 'Skill checks', 'Trace / knob mid-sweep & invalid', 'Injected knob output: 45% at 0.6s, a dropped native sample at 1s, 70% at 2s.', [m('skill:open', { session: 1, config: skillConfig('trace', { direction: 'lower' }) }), m('skill:trace', { session: 1, progress: .45, invalid: false }, 600), m('skill:trace', { session: 1, progress: .45, invalid: true }, 1000), m('skill:trace', { session: 1, progress: .7, invalid: false }, 2000)]);
add('skill-outcome-clear', 'Skill checks', 'Outcome / clear', 'Injected knob progress, then a Lua success: the slip tag shows briefly and leaves.', [m('skill:open', { session: 1, config: skillConfig('trace') }), m('skill:trace', { session: 1, progress: .8, invalid: false }, 500), m('skill:close', { session: 1, success: true, reason: 'success' }, 900)]);
add('skill-outcome-missed', 'Skill checks', 'Outcome / missed', 'A Lua miss on the radial: soft red slip tag.', [m('skill:open', { session: 1, config: skillConfig('radial') }), m('skill:close', { session: 1, success: false, reason: 'missed' }, 900)]);
add('skill-mash-progress', 'Skill checks', 'Mash / mid progress', 'Injected accepted taps: the ring fills against decay and the keycap presses.', [m('interaction:world', { items: [world({ id: 'mash', label: 'Build pressure' })] }), m('skill:open', { session: 1, owner: 'browser-lab', config: skillConfig('mash', { decay: .05 }) }), m('skill:progress', { session: 1, progress: .6 }, 300)], { behavior: 'skill-mash' });
add('debug-workbench', 'Debug workbench', 'Workbench menu', 'The shipped workbench, populated with browser fixture entries. Running an entry opens its lab scenario.', [m('debug:open', { session: 1, history: [], catalog: [{ id: 'notify_info', title: 'Information notice', group: 'Notifications', description: 'Browser fixture' }, { id: 'settings_all', title: 'Settings', group: 'Settings', description: 'Browser fixture' }, { id: 'anchor_hold', title: 'Hold prompt', group: 'Interactions', description: 'Browser fixture' }] })]);
add('debug-walkthrough', 'Debug workbench', 'Test All progress', 'The production walkthrough indicator with simulated completion updates.', [m('debug:walkthrough', { revision: 1, run: { index: 1, completed: 0, total: 3, id: 'first', title: 'Notifications' } }), m('debug:walkthrough', { revision: 2, run: { index: 2, completed: 1, total: 3, id: 'second', title: 'Settings' } }, 1800), m('debug:walkthrough', { revision: 3, run: { index: 3, completed: 3, total: 3, id: 'third', title: 'Complete' } }, 3600)]);
const profile = { accent: '#8fcbbf', opacity: 92, scale: 100, motion: 'full' };
add('presentation', 'Layout & lifecycle', 'Safe zone / dynamic layout', 'Mock viewport and occupied surface geometry exercise the real shared presentation adapter.', [m('notify', notice()), m('interaction:update', { items: [prompt()] }), m('textUIShow', { text: 'Layout collision specimen', position: 'bottom-left' }), m('cortex:presentation', { v: 1, revision: 1, profile, viewport: { width: 1920, height: 1080, inset: 80 }, surfaces: [{ key: 'mock-hud', owner: 'cortex-hud', fixed: true, x: 20, y: 800, width: 500, height: 260, priority: 100 }] })]);
add('reduced-motion', 'Layout & lifecycle', 'Reduced motion', 'Shared presentation reduced-motion profile. OS reduced-motion preferences also apply to the UI.', [m('cortex:presentation', { v: 1, revision: 1, profile: { ...profile, motion: 'reduced' }, viewport: { width: 1920, height: 1080, inset: 40 }, surfaces: [] }), m('notify', notice()), m('interaction:update', { items: [prompt()] })]);
add('lifecycle', 'Layout & lifecycle', 'Open, close & stale sessions', 'Open a menu, reject a stale close at 1s, close at 2s, reopen at 3s.', [m('menuOpen', menu()), m('menuClose', { session: 99 }, 1000), m('menuClose', { session: 1 }, 2000), m('menuOpen', menu({ session: 2, title: 'Reopened session' }), 3000)]);
add('malformed', 'Layout & lifecycle', 'Malformed messages', 'Malformed and unknown messages followed by a valid notice to check that rendering remains usable.', [m('unknown:action'), m('interaction:world', { items: [{ x: 'invalid', key: null }] }), m('notify', { type: 'invalid', description: null }), m('menuOpen', { options: [null, 42], session: 'bad' }), m('menuClose'), m('notify', notice('success', { title: 'Valid message after malformed input' }), 500)]);

export { scenarios };
